# Generated by Django 5.1.7 on 2025-03-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
