# Generated by Django 5.1.7 on 2025-03-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_name_alter_project_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
