version: '3.9'

services:
  django-web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py loaddata technology.json && python manage.py loaddata project_data.json && gunicorn project_presenter.wsgi:application --bind 0.0.0.0:8000"
    container_name: django-docker
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-env}
